export const skillsData = [
  { icon: 'react', title: 'React', proficiency: 'Advanced' },
  { icon: 'html5', title: 'HTML5', proficiency: 'Advanced' },
  { icon: 'javascript', title: 'JavaScript', proficiency: 'Advanced' },
  { icon: 'typescript', title: 'TypeScript', proficiency: 'Advanced' },
  { icon: 'python', title: 'Python', proficiency: 'Advanced' },
  { icon: 'css3', title: 'CSS3', proficiency: 'Advanced' },
  { icon: 'nodejs', title: 'NodeJS', proficiency: 'Advanced' },
  { icon: 'webpack', title: 'Webpack', proficiency: 'Intermediate' },
  {
    icon: 'amazonwebservices',
    title: 'AWS',
    proficiency: 'AWS Certified Cloud Practitioner',
    jumpUrl:
      'https://www.credly.com/badges/00a02495-e272-4c59-ae66-fbf6ea79d788?source=linked_in_profile',
  },
  { icon: 'java', title: 'Java', proficiency: 'Intermediate' },
  { icon: 'cplusplus', title: 'C++', proficiency: 'Intermediate' },
  { icon: 'c', title: 'C', proficiency: 'Intermediate' },
  { icon: 'mysql', title: 'MySQL', proficiency: 'Intermediate' },
  { icon: 'flutter', title: 'Flutter', proficiency: 'Intermediate' },
  { icon: 'docker', title: 'Docker', proficiency: 'Beginner' },
  { icon: 'csharp', title: 'C#', proficiency: 'Beginner' },
  { icon: 'php', title: 'PHP', proficiency: 'Beginner' },
  { icon: 'photoshop', title: 'PhotoShop', proficiency: 'Beginner' },
  { icon: 'premierepro', title: 'PremierePro', proficiency: 'Beginner' },
];
